# ===================================
# APPLICATION CONFIG
# ===================================
spring.application.name=authentication
server.port=${SERVER_PORT}

# ===================================
# MONGODB ATLAS
# ===================================
spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.database=${MONGODB_DATABASE}

# ===================================
# JWT CONFIG
# ===================================
jwt.secret=${JWT_SECRET}

# ===================================
# DEVTOOLS
# ===================================
spring.devtools.restart.enabled=true

#
#logging.level.org.mongodb.driver.cluster=DEBUG
#logging.level.org.springframework.data.mongodb=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
from.mail=${FROM_MAIL}
spring.mail.username=${HOST_EMAIL}
spring.mail.password=${HOST_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true